#!/bin/sh
#
# @name Hexarotor x with tilted arms
#
# @url http://theairlab.org/
#
# @type Tilt-Hexarotor
# @class Copter
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Azarakhsh Keipour <keipour@cmu.edu>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_P 0.100
param set-default MC_PITCHRATE_I 0.0400
param set-default MC_PITCHRATE_D 0.0100
param set-default MC_PITCH_P 16.0
param set-default MC_ROLLRATE_P 0.100
param set-default MC_ROLLRATE_I 0.0400
param set-default MC_ROLLRATE_D 0.0100
param set-default MC_ROLL_P 16.0
param set-default MPC_XY_VEL_I_ACC 3
param set-default MPC_XY_VEL_P_ACC 3

param set-default RTL_DESCEND_ALT 10
param set-default EKF2_DECL_TYPE 4 # solve for the mag drift issue in gazebo
param set-default EKF2_MAG_TYPE 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_METHOD 1

param set-default EKF2_HGT_REF 0

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 1.0
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_AX 0.5
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -0.866025

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -1.0
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_AX 0.5
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -0.866025

param set-default CA_ROTOR2_PX 0.866025
param set-default CA_ROTOR2_PY -0.5
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_AX -0.25
param set-default CA_ROTOR2_AY -0.4330125
param set-default CA_ROTOR2_AZ -0.866025

param set-default CA_ROTOR3_PX -0.866025
param set-default CA_ROTOR3_PY 0.5
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR3_AX -0.25
param set-default CA_ROTOR3_AY -0.4330125
param set-default CA_ROTOR3_AZ -0.866025

param set-default CA_ROTOR4_PX 0.866025
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR4_AX -0.25
param set-default CA_ROTOR4_AY 0.4330125
param set-default CA_ROTOR4_AZ -0.866025

param set-default CA_ROTOR5_PX -0.866025
param set-default CA_ROTOR5_PY -0.5
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR5_AX -0.25
param set-default CA_ROTOR5_AY 0.4330125
param set-default CA_ROTOR5_AZ -0.866025

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106